# Generated by Django 3.2 on 2021-10-22 17:24

import ATTENDANCE.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNT', '0003_auto_20211017_1426'),
        ('ATTENDANCE', '0002_alter_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='standard',
            field=models.CharField(choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=ATTENDANCE.models.today_date)),
                ('mark', models.PositiveIntegerField()),
                ('total_score', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_name', to='ACCOUNT.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject', to='ATTENDANCE.subject')),
            ],
        ),
    ]
